//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.15 at 10:16:16 AM ALMT 
//


package io.spring.guides.gs_producing_web_service;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for weather.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="weather"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Sunny"/&gt;
 *     &lt;enumeration value="Cloudy"/&gt;
 *     &lt;enumeration value="Rainy"/&gt;
 *     &lt;enumeration value="Snowy"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "weather")
@XmlEnum
public enum Weather {

    @XmlEnumValue("Sunny")
    SUNNY("Sunny"),
    @XmlEnumValue("Cloudy")
    CLOUDY("Cloudy"),
    @XmlEnumValue("Rainy")
    RAINY("Rainy"),
    @XmlEnumValue("Snowy")
    SNOWY("Snowy");
    private final String value;

    Weather(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Weather fromValue(String v) {
        for (Weather c: Weather.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
